addons:
  apt:
    packages:
      - git
      - make
      - curl

matrix:
  include:
    - env: TERRAFORM_VERSION=0.12.6
  allow_failures:
    - env: TERRAFORM_VERSION=0.11.11

install:
  - make init

script:
  - make terraform/install
  - make terraform/get-plugins
  - make terraform/get-modules
  - make terraform/lint
  - make terraform/validate
